import { Context } from 'hono';
import { LOGO_PNG_BASE64, LOGO_SVG } from '../../../generated/logo-assets';

/**
 * Serve the PuppyGirl logo from the Worker itself.
 *
 * `branding.json` used to point every icon at `assets.fxembed.com` and Twitter's favicon CDN — so
 * each embed advertised someone else's logo, and the icons would break silently if either host
 * moved a path or blocked hotlinking. The bytes are generated by `tools/make-logo.mjs`, committed,
 * and inlined into the bundle, which removes the third-party dependency entirely.
 */

const ONE_YEAR = 'public, max-age=31536000, immutable';

/* Decoded once per isolate rather than per request; the set is a few KB.
   Explicitly backed by ArrayBuffer (not the wider ArrayBufferLike, which admits SharedArrayBuffer)
   because that is what a response body accepts. */
const pngCache = new Map<string, Uint8Array<ArrayBuffer>>();

const decode = (base64: string): Uint8Array<ArrayBuffer> =>
  Uint8Array.from(atob(base64), char => char.charCodeAt(0));

export const logoRoute = async (c: Context) => {
  const name = c.req.param('name') ?? '';

  if (name === 'puppygirl.svg') {
    return c.body(LOGO_SVG, 200, {
      'Content-Type': 'image/svg+xml',
      'Cache-Control': ONE_YEAR
    });
  }

  /* `puppygirl32.png` -> 32. Anything else is not one of ours. */
  const size = name.match(/^puppygirl(\d{1,3})\.png$/)?.[1];
  const base64 = size ? LOGO_PNG_BASE64[size] : undefined;

  if (!base64) {
    return c.notFound();
  }

  let bytes = pngCache.get(size!);
  if (!bytes) {
    bytes = decode(base64);
    pngCache.set(size!, bytes);
  }

  return c.body(bytes, 200, {
    'Content-Type': 'image/png',
    'Cache-Control': ONE_YEAR,
    /* These are static bytes we generated, but they are still served to browsers. */
    'X-Content-Type-Options': 'nosniff'
  });
};
